apiVersion: v1
kind: Secret
metadata:
  name: secretdocker
type: kubernetes.io/basic-auth
stringData:
  username: muruganhub # required field for kubernetes.io/basic-auth
  password: Sureshraina@3 # required field for kubernetes.io/basic-auth
